# filename: manager.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

# agents/manager.py

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from google import genai
from google.genai import types
from dotenv import load_dotenv

from agents import qualitative, quantitative
from validation.validator import validate_qualitative, validate_quantitative
from tokenomics.logger import log

load_dotenv()

client = genai.Client()

MODEL = "gemini-3.5-flash-lite"


def classify(query: str) -> str:
    response = client.models.generate_content(
        model=MODEL,
        contents=f"""Classify this query as exactly one of: qualitative, quantitative, both.

qualitative = questions about policies, processes, procedures, explanations, documentation
quantitative = questions about numbers, metrics, trends, comparisons, SQL-queryable data
both = questions that need both document search and data analysis

Query: {query}

Reply with one word only: qualitative, quantitative, or both.""",
        config=types.GenerateContentConfig(
            max_output_tokens=10,
            automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
        ),
    )

    route = (response.text or "").strip().lower()

    usage = response.usage_metadata
    log(
        query,
        "manager-classifier",
        usage.prompt_token_count,
        usage.candidates_token_count,
    )

    return route if route in ["qualitative", "quantitative", "both"] else "qualitative"


def run(query: str):
    print(f"\nQuery: {query}")
    route = classify(query)
    print(f"Route: {route}")

    qual_result = None
    quant_result = None

    if route in ["qualitative", "both"]:
        qual_result = qualitative.run(query)
        validation = validate_qualitative(qual_result["answer"], qual_result["chunks"])
        log(query, "qualitative", qual_result["input_tokens"], qual_result["output_tokens"])
        if validation["flag"]:
            print(f"\n⚠️  VALIDATION WARNING: {validation['warning']}")
        print(f"\n[Qualitative]\n{qual_result['answer']}")

    if route in ["quantitative", "both"]:
        quant_result = quantitative.run(query)
        validation = validate_quantitative(
            quant_result["answer"],
            quant_result["sql"],
            quant_result["validation"],
        )
        log(query, "quantitative", quant_result["input_tokens"], quant_result["output_tokens"])
        if validation["flag"]:
            print(f"\n⚠️  VALIDATION WARNING: {validation['warning']}")
        print(f"\n[Quantitative]\n{quant_result['answer']}")
        print(f"SQL used: {quant_result['sql']}")

    return {"route": route, "qualitative": qual_result, "quantitative": quant_result}


if __name__ == "__main__":
    print("Manager agent ready. Type 'quit' or 'exit' to stop.")
    while True:
        user_query = input("\nEnter question: ").strip()
        if user_query.lower() in ("quit", "exit", "q"):
            print("Goodbye.")
            break
        if not user_query:
            continue
        run(user_query)
